# Generated by Django 2.1.2 on 2018-10-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Found',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
