# Generated by Django 2.1.2 on 2018-10-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0002_found'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
