# Generated by Django 2.1.2 on 2018-10-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0008_auto_20181026_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='found',
            name='pic',
            field=models.ImageField(default='https://www.google.co.in/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjt3fWzq6TeAhXEuI8KHSdeB5sQjRx6BAgBEAU&url=https%3A%2F%2Fwww.freepik.com%2Ffree-icon%2Fuser-profile-avatar_754395.htm&psig=AOvVaw1O3TOPFz305U5bSuN5MZTC&ust=1540651278631657', upload_to='profile_pics'),
        ),
    ]
