# Generated by Django 2.1.2 on 2018-10-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0010_auto_20181026_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='found',
            name='pic',
            field=models.ImageField(upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='lost',
            name='pic',
            field=models.ImageField(blank=True, default='def.jpg', upload_to=''),
        ),
    ]
