# Generated by Django 2.1.2 on 2018-10-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(blank=True, choices=[('Chennai', 'Chennai'), ('Delhi', 'Delhi'), ('Bombay', 'Bombay'), ('Tirupati', 'Tirupati'), ('Agra', 'Agra')], max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='city',
            field=models.CharField(blank=True, choices=[('Chennai', 'Chennai'), ('Delhi', 'Delhi'), ('Bombay', 'Bombay'), ('Tirupati', 'Tirupati'), ('Agra', 'Agra')], max_length=130, null=True),
        ),
    ]
