# Generated by Django 2.1.2 on 2018-10-25 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181025_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='status',
        ),
    ]
