# Generated by Django 2.1.2 on 2018-10-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181025_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='cityname',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
