# Generated by Django 2.1.2 on 2018-10-26 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181026_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(blank=True, choices=[('Forest_Fire', 'Forest_Fire'), ('Flood', 'Flood'), ('tora', 'tora')], max_length=130, null=True)),
                ('unsafe_peoples', models.BigIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, choices=[('Chennai', 'Chennai'), ('Delhi', 'Delhi'), ('Bombay', 'Bombay'), ('Tirupati', 'Tirupati'), ('Agra', 'Agra')], max_length=130, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(blank=True, choices=[('Forest_Fire', 'Forest_Fire'), ('Flood', 'Flood'), ('tora', 'tora')], max_length=130, null=True)),
                ('status', models.CharField(choices=[('Safe', 'Safe'), ('Unsafe', 'Unsafe')], max_length=130)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='city',
            field=models.CharField(blank=True, choices=[('Chennai', 'Chennai'), ('Delhi', 'Delhi'), ('Bombay', 'Bombay'), ('Tirupati', 'Tirupati'), ('Agra', 'Agra')], max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='city_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.City'),
        ),
    ]
